spring.application.name=url-shortener

# Server port
server.port=8080


# This allows access from outside the container (e.g., your browser)
spring.datasource.url=jdbc:h2:mem:urlshortener;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL

# H2 in-memory database configuration
# spring.datasource.url=jdbc:h2:mem:urlshortener;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show H2 console in browser at /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Enable SQL logging (for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=trued
spring.web.resources.add-mappings=true